/**
 * @copyright Copyright (c) 2020 Maxim Khorin <maksimovichu@gmail.com>
 */
'use strict';

Object.assign(Jam.I18n.defaults, {

    'Abstract': 'Абстрактный',    
    'Action binder': 'Настройка действий',
    'Actions': 'Действия',
    'Actions with attribute depending on the current object values': 'Действия с атрибутом, зависящие от текущих значений объекта',
    'Activation': 'Активация',
    'Active': 'Активно',
    'Active descendants': 'Активные наследники',
    'Ascending': 'По возрастанию',
    'Additional attribute functionality': 'Дополнительная функциональность атрибута',
    'Additional class functionality': 'Дополнительная функциональность класса',
    'Assigned value': 'Назначаемое значение',
    'Assigned value options': 'Параметры назначаемого значения',
    'All studio data will be overwritten': 'Все данные студии будут перезаписаны',
    'Attribute': 'Атрибут',
    'Attribute requirement condition': 'Условие обязательности атрибута',
    'Attribute availability condition': 'Условие доступности атрибута',
    'Attribute visibility condition': 'Условие показа атрибута',
    'Attributes': 'Атрибуты',
    'Auto-generated key is used for empty value': 'При пустом значени используется автогенерируемый ключ',
    'Auto increment': 'Автоматическое приращение',
    'Auto increment options': 'Параметры автоматического приращения',

    'Back reference': 'Обратная ссылка',
    'Background': 'Фоновый',
    'Base class that cannot be instantiated directly': 'Экземпляры базового класса не могут быть созданы напрямую',
    'Behavior': 'Поведение',
    'Behaviors': 'Поведения',
    'Boolean': 'Логический',

    'Calculated': 'Вычисляемый',
    'Calculated expression': 'Вычисляемое выражение',
    'Cascade': 'Каскад',
    'Child groups': 'Дочерние группы',
    'Children': 'Дети',
    'Class': 'Класс',
    'Class attribute': 'Атрибут класса',
    'Class attributes': 'Атрибуты класса',
    'Class configuration': 'Конфигурация класса',
    'Class group': 'Группа класса',
    'Class of related objects': 'Класс связанных объектов',
    'Classes': 'Классы',
    'Clear': 'Очистить',
    'Clone from parent class': 'Клонировать из родительского класса',
    'Code name': 'Кодовое имя',
    'Column container': 'Контейнер колонок',
    'Commands': 'Команды',
    'Common searchable': 'Общий поисковый',
    'Condition': 'Условие',
    'Condition of setting a specific value to attribute': 'Условие задания определенного значения атрибуту',
    'Configuration': 'Конфигурация',
    'Configuration of custom class for selecting related objects': 'Конфигурация пользовательского класса для выбора связанных объектов',
    'Create action binder': 'Создать настройку действий',
    'Create attribute': 'Создать атрибут',
    'Create behavior': 'Создать поведение',
    'Create by class attributes': 'Создать по атрибутам класса',
    'Create by class groups': 'Создать по группам класса',
    'Create class': 'Создать класс',
    'Create class attribute': 'Создать атрибут класса',
    'Create class index': 'Создать индекс класса',
    'Create enum': 'Создать перечисление',
    'Create enum item': 'Создать элемент перечисления',
    'Create group': 'Создать группу',
    'Create index': 'Создать индекс',
    'Create navigation node': 'Создать пункт навигации',
    'Create navigation section': 'Создать секцию навигации',
    'Create node': 'Создать пункт',
    'Create relation': 'Создать отношение',
    'Create rule': 'Создать правило',
    'Create state': 'Создать состояние',
    'Create timestamp': 'Метка создания',
    'Create transition': 'Создать переход',
    'Create tree level': 'Создать уровень',
    'Create validation rule': 'Создать правило валидации',
    'Create view': 'Создать представление',
    'Create view attribute': 'Создать атирбут представления',
    'Current attribute is used for empty value': 'При пустом значении используется текущий атрибут',
    'Custom behavior': 'Пользовательское поведение',
    'Custom behavior options': 'Параметры пользовательского поведения',
    'Custom validator': 'Пользовательский валидатор',
    'Custom validator options': 'Параметры пользовательской валидации',

    'Date': 'Дата',
    'Date and time': 'Дата и время',
    'Defaults': 'По умолчанию',
    'Delete absolutely all studio data?': 'Удалить абсолютно все данные студии?',
    'Descending': 'По убыванию',
    'Direction': 'Направление',
    'Disable groups': 'Отключить группы',
    'Disable tree view': 'Отключить древовид',
    'Drop duplicates': 'Удалять дубли',

    'Eager depth': 'Глубина жадной загрузки',
    'Eager loading': 'Жадная загрузка',
    'Eager view': 'Жадное представление',
    'Editor': 'Редактор',
    'Enable': 'Активировать',
    'Enum': 'Перечисление',
    'Enum item': 'Элемент перечисления',
    'Enums': 'Перечисления',
    'Error message': 'Сообщение об ошибке',
    'Escape': 'Экранировать',
    'Escape HTML data output': 'Экранировать вывод HTML данных',
    'Expanded group or active tab': 'Развернутая группа или активная вкладка',
    'Export': 'Экспортировать',
    'Export class': 'Экспортировать класс',
    'Export metadata': 'Экспортировать метаданные',
    'Export navigation section': 'Экспортировать секцию навигации',
    'Export section': 'Экспортировать секцию',
    'Export view': 'Экспортировать представление',
    'Expression': 'Выражение',
    'Expression options': 'Параметры выражения',
    'Extended hint': 'Расширенная подсказка',
    'Extensions': 'Расширения',

    'Featured classes for creating objects': 'Избранные классы для создания объектов',
    'File': 'Файл',
    'File options': 'Файловые параметры',
    'Filename attribute': 'Атрибут имени файла',
    'Filter': 'Фильтр',
    'Filter condition to search for unique values.\nInput attribute name to create a filter by value of this attribute': 'Условие фильтра для поиска уникальных значений.\nВведите имя атрибута для создания фильтра по значению этого атрибута',
    'Filter selected files by type (e.g. image/*)': 'Фильтровать выбираемые файлы по типу (например, image/*)',
    'Final state': 'Конечное состояние',
    'Final states': 'Конечные состояния',
    'Finishing transitions': 'Заканчивающиеся переходы',
    'Flags': 'Флаги',
    'Float': 'Вещественный',

    'Grouping': 'Группировка',
    'Group': 'Группа',
    'Groups': 'Группы',

    'Header template': 'Шаблон заголовка',
    'Hidden': 'Скрытый',
    'Hierarchy': 'Иерархия',
    'Hint': 'Подсказка',
    'History': 'История',

    'Identifier': 'Идентификатор',
    'Ignore case': 'Игнорировать регистр',
    'Ignore unique value case': 'Игнорировать регистр уникальных значений',
    'Image only': 'Только изображения',
    'Import class': 'Импортировать класс',
    'Import metadata': 'Импортировать метаданные',
    'Import section': 'Импортировать секцию',
    'Import view': 'Импортировать представление',
    'In bytes': 'В байтах',
    'Index': 'Индекс',
    'Indexes': 'Индексы',
    'Indexing': 'Индексирование',
    'Inherit': 'Наследовать',
    'Inherited': 'Унаследованно',
    'Integer': 'Целое',
    'Integer only': 'Только целые',
    'Invalid class file': 'Неверный файл класса',
    'Invalid code name': 'Неверное кодовое имя',
    'Items': 'Элементы',
    'Intermediate link': 'Промежуточная связь',
    'Is not integer': 'Не является целым числом',
    'Is not sortable': 'Не является сортируемым',

    'JSON editor': 'Редактор JSON',

    'Key': 'Ключ',
    'Key attribute is used for empty value': 'При пустом значении используется ключевой атрибут',

    'Length': 'Длина',
    'Limiting loading depth of related objects': 'Ограничение глубины загрузки связанных объектов',
    'Link attribute': 'Атрибут связи',
    'List view': 'Представление списка',
    'Load related objects along with the main': 'Загружать связанные объекты вместе с основным',
    'Local date': 'Локальная дата',
    'Local date and time': 'Локальная дата и время',
    'Location': 'Местоположение',

    'Main': 'Основные',
    'Many related objects are possible': 'Возможно множество связанных объектов',
    'Maximum': 'Максимум',
    'Maximum files': 'Максимум файлов',
    'Maximum items': 'Максимум объектов',
    'Maximum length': 'Максимальная длина',
    'Maximum objects': 'Максимум объектов',
    'Maximum size': 'Максимальный размер',
    'Maximum total size': 'Предел общего размера',
    'Maximum value': 'Максимальное значение',
    'Message': 'Сообщение',
    'Mediation to select related objects': 'Промежуточная связь для выбора связанных объектов',
    'Metadata directory relative to application root': 'Директория метаданных относительно корня приложения',
    'MIME types': 'MIME типы',
    'Minimum': 'Минимум',
    'Minimum files': 'Минимум файлов',
    'Minimum length': 'Минимальная длина',
    'Minimum items': 'Минимум объектов',
    'Minimum objects': 'Минимум объектов',
    'Minimum size': 'Минимальный размер',
    'Minimum value': 'Минимальное значение',
    'Mismatch': 'Несовпадение',
    'Mismatch (valid if pattern does not match)': 'Несовпадение (валидно, если не соответствует шаблону)',
    'Model configuration': 'Конфигурация модели',
    'Multiple': 'Множественное',

    'Navigation': 'Навигация',
    'Navigation node': 'Пункт навигации',
    'Navigation nodes': 'Пункты навигации',
    'Navigation section': 'Секция навигации',
    'Navigation sections': 'Секции навигации',
    'Nested groups': 'Вложенные группы',
    'Node': 'Пункт',
    'Nodes': 'Пункты',
    'None': 'Нет',
    'Null start state': 'Пустое начальное состояние',
    'Number': 'Число',
    'Number options': 'Числовые параметры',

    'Object filter': 'Объектный фильтр',
    'Object list grouping': 'Группировка объектов в списке',
    'Object list order': 'Порядок объектов в списке',
    'Object selection condition': 'Условие выборки объектов',
    'On delete': 'При удалении',
    'On delete reference class instance:\nCascade - delete relation owner instance\nNull - empty linked attribute value': 'При удалении объекта ссылочного класса:\nКаскад - удалять объект владельца данного отношения\nNull - обнулять атрибут связи',
    'On update': 'При обновлении',
    'On update reference class instance:\nCascade - update linked attribute value\nNull - empty linked attribute value': 'При обновлении объекта ссылочного класса:\nКаскад - обновлять атрибут связи\nNull - обнулять атрибут связи',
    'Options': 'Опции',
    'Orderable': 'Упорядочиваемый',    
    'Original': 'Оригинал',
    'Override': 'Переопределить',
    'Owner': 'Владелец',

    'Param': 'Параметр',
    'Params': 'Параметры',
    'Parent': 'Родитель',
    'Parent class attribute': 'Атрибут родительского класса',
    'Parent group': 'Родительская группа',
    'Parent node': 'Родительский пункт',
    'Pattern': 'Шаблон',
    'Predefined sets of named values': 'Предопределенные наборы именованных значений',
    'Primary key': 'Первичный ключ',

    'Read-only object mode': 'Режим объекта только для чтения',
    'Read only': 'Только чтение',
    'Reference': 'Ссылка на объект',
    'Reference attribute': 'Ссылочный атирбут',
    'Reference class': 'Ссылочный класс',
    'Regular expression': 'Регулярное выражение',
    'Regular expression options': 'Параметры регулярного выражения',
    'Relation': 'Отношение',
    'Relation counter': 'Счетчик отношения',
    'Relation counter options': 'Параметры счетчика отношения',
    'Remove whitespace from both string ends': 'Удалить пустые символы с обоих концов строки',
    'Report': 'Отчет',
    'Reports': 'Отчеты',
    'Require': 'Требовать',
    'Required': 'Обязательный',
    'Recursive': 'Рекурсивный',
    'Rule': 'Правило',
    'Rules': 'Правила',

    'Save changes first': 'Сначала сохраните изменения',
    'Save data change history': 'Сохранять историю изменения данных',
    'Search': 'Поиск',
    'Search depth': 'Глубина поиска',
    'Search view': 'Представление поиска',
    'Searchable': 'Поисковый',
    'Section': 'Секция',
    'Select list view': 'Представление выбора',
    'Select searchable': 'Поисковый в списке выбора',
    'Separate with comma': 'Разделять запятой',
    'Setting': 'Настройка',
    'Show': 'Показать',
    'Sort': 'Сортировать',
    'Sort order': 'Порядок сортировки',
    'Sort order options': 'Параметры порядка сортировки',
    'Sortable': 'Сортируемый',
    'Sortable by owner (non-indexable sorting)': 'Сортируемый по владельцу (не индексируемая выборка)',
    'Sorting': 'Сортировка',
    'Source': 'Источник',
    'Source class': 'Исходный класс',
    'Spawn configuration': 'Конфигурация создания',
    'Start': 'Начало',
    'Start state': 'Начальное состояние',
    'Start states': 'Начальные состояния',
    'Start value': 'Начальное значение',
    'Starting transitions': 'Начинающиеся переходы',
    'State': 'Состояние',
    'States': 'Состояния',
    'Step': 'Шаг',
    'Stored data type': 'Тип хранимых данных',
    'String': 'Строка',
    'String options': 'Строковые параметры',
    'String view template': 'Шаблон строкового представления',
    'String view template of object': 'Шаблон строкового представления объекта',
    'System attribute must be read only': 'Системный атрибут должен быть только для чтения',

    'Tab container': 'Контейнер вкладок',
    'Template root': 'Корень шаблонов',
    'Text': 'Текст',
    'Thumbnail': 'Миниатюра',
    'Time': 'Время',
    'Timestamp': 'Метка времени',
    'Timestamp options': 'Параметры метки времени',
    'Title': 'Заголовок',
    'Transit configuration': 'Конфигурация перехода',
    'Transition': 'Переход',
    'Transition is available if condition is true': 'Переход доступен, если условие истинно',
    'Transitions': 'Переходы',
    'Tree level': 'Уровень иерархии',
    'Tree view': 'Древовид',
    'Tree view levels': 'Древовидные уровни',

    'Unable to delete inherited attribute': 'Нельзя удалить унаследованный атрибут',
    'Unique': 'Уникальный',
    'Update indexes': 'Обновить индексы',
    'Update timestamp': 'Метка обновления',
    'User': 'Пользователь',

    'Validation': 'Валидация',
    'Value': 'Значение',
    'Value attribute': 'Атрибут значения',
    'Valued': 'Имеющий значение',
    'Via': 'Через',
    'View': 'Представление',
    'View attribute': 'Атрибут представления',
    'View attributes': 'Атрибуты представления',
    'View groups': 'Группы представления',
    'View rule': 'Правило представления',
    'View to display related objects in a list': 'Представление для отображения связанных объектов в списке',
    'View to display objects in selection list': 'Представление для отображения объектов в списке выбора',
    'View type': 'Тип представления',
    'Views': 'Представления',

    'Workflow': 'Бизнес-процесс',
    'Workflow state': 'Состояние бизнес-процесса'
});