/**
 * @copyright Copyright (c) 2020 Maxim Khorin <maksimovichu@gmail.com>
 */
'use strict';

Object.assign(Jam.I18n.defaults, {

    'Abstract class': 'Абстрактный класс',
    'Abstract class cannot be instantiated': 'Абстрактный класс не может использоваться для создания объектов',
    'Action binder': 'Настройка действий',
    'Action binders': 'Настройки действий',
    'Actions': 'Действия',
    'Actions with attribute depending on the current object values': 'Действия с атрибутом, зависящие от текущих значений объекта',
    'Activation': 'Активация',
    'Active': 'Активно',
    'Active descendants': 'Активные наследники',
    'Add view from parent class': 'Добавить представление из родительского класса',
    'Additional attribute functionality': 'Дополнительная функциональность атрибута',
    'Additional class functionality': 'Дополнительная функциональность класса',
    'Additional class parameters': 'Дополнительные параметры класса',
    'Assigned value': 'Назначаемое значение',
    'Assigned value options': 'Параметры назначаемого значения',
    'All attributes in this group are read-only': 'Все атрибуты в этой группе только для чтения',
    'All attributes in this group are required': 'Все атрибуты в этой группе обязательные',
    'All studio data will be overwritten': 'Все данные студии будут перезаписаны',
    'Allow to create related objects on read-only mode': 'Разрешить создавать связанные объекты при режиме только чтение',
    'Ascending': 'По возрастанию',
    'Attribute': 'Атрибут',
    'Attribute availability condition': 'Условие доступности атрибута',
    'Attribute requirement condition': 'Условие обязательности атрибута',
    'Attribute that gets filename on upload': 'Атрибут, который получает имя файла при загрузке',
    'Attribute value cannot be empty': 'Значение атрибута не может быть пустым',
    'Attribute value must be unique': 'Значение атрибута должно быть уникальным',
    'Attribute visibility condition': 'Условие показа атрибута',
    'Attributes': 'Атрибуты',
    'Auto-generated key is used for empty value': 'При пустом значени используется автогенерируемый ключ',
    'Auto increment': 'Автоматическое приращение',
    'Auto increment options': 'Параметры автоматического приращения',

    'Back reference': 'Обратная ссылка',
    'Background build': 'Фоновая сборка',
    'Behavior': 'Поведение',
    'Behaviors': 'Поведения',
    'Boolean': 'Логический',
    'Build the index without blocking other database activity': 'Построение индекса без блокировки других операций с базой данных',

    'Calculated': 'Вычисляемый',
    'Calculated expression': 'Вычисляемое выражение',
    'Calculated expression options': 'Параметры вычисляемого выражения',
    'Cascade': 'Каскадное действие',
    'Change step': 'Шаг изменения',
    'Child groups': 'Дочерние группы',
    'Children': 'Наследники',
    'Class': 'Класс',
    'Class attribute': 'Атрибут класса',
    'Class attributes': 'Атрибуты класса',
    'Class configuration': 'Конфигурация класса',
    'Class group': 'Группа класса',
    'Class imported': 'Класс импортирован',
    'Class of related objects': 'Класс связанных объектов',
    'Classes': 'Классы',
    'Clear': 'Очистить',
    'Clone from other classes': 'Клонировать из других классов',
    'Clone from parent classes': 'Клонировать из родительских классов',
    'Code name': 'Кодовое имя',
    'Column container': 'Контейнер колонок',
    'Commands': 'Команды',
    'Common searchable': 'Общий поисковый',
    'Condition': 'Условие',
    'Condition of setting a specific value to attribute': 'Условие задания определенного значения атрибуту',
    'Condition options': 'Параметры условия',
    'Configuration': 'Конфигурация',
    'Create action binder': 'Создать настройку действий',
    'Create attribute': 'Создать атрибут',
    'Create behavior': 'Создать поведение',
    'Create by class attributes': 'Создать по атрибутам класса',
    'Create by class groups': 'Создать по группам класса',
    'Create class': 'Создать класс',
    'Create class attribute': 'Создать атрибут класса',
    'Create class index': 'Создать индекс класса',
    'Create enum': 'Создать перечисление',
    'Create enum item': 'Создать элемент перечисления',
    'Create group': 'Создать группу',
    'Create index': 'Создать индекс',
    'Create intermediate link': 'Создать промежуточную связь',
    'Create navigation node': 'Создать пункт навигации',
    'Create navigation section': 'Создать секцию навигации',
    'Create node': 'Создать пункт',
    'Create on read': 'Создавать при чтении',
    'Create relation': 'Создать отношение',
    'Create report': 'Создать отчет',
    'Create rule': 'Создать правило',
    'Create state': 'Создать состояние',
    'Create timestamp': 'Метка создания',
    'Create transition': 'Создать переход',
    'Create tree level': 'Создать древовидный уровень',
    'Create validation rule': 'Создать правило валидации',
    'Create view': 'Создать представление',
    'Create view attribute': 'Создать атирбут представления',
    'Creation view': 'Представление создания',
    'Current attribute is used for empty value': 'При пустом значении используется текущий атрибут',
    'Custom behavior': 'Пользовательское поведение',
    'Custom behavior options': 'Параметры пользовательского поведения',
    'Custom validator': 'Пользовательский валидатор',
    'Custom validator options': 'Параметры пользовательской валидации',

    'Date': 'Дата',
    'Date and time': 'Дата и время',
    'Defaults': 'По умолчанию',
    'Delete all studio data?': 'Удалить все данные студии?',
    'Delete related objects after unlink or relation owner deletion': 'Удалить связанные объекты после удаления связи или владельца отношения',
    'Descending': 'По убыванию',
    'Direction': 'Направление',
    'Disable groups': 'Отключить группы',
    'Disable tree view': 'Отключить древовид',
    'Divider': 'Разделитель',
    'Drop duplicates': 'Удалять дубли',
    'Dropdown selector search': 'Поиск в выпадающем списке',

    'Eager depth': 'Глубина жадной загрузки',
    'Eager loading': 'Жадная загрузка',
    'Eager view': 'Жадное представление',
    'Editor': 'Редактор',
    'Edit view': 'Представление редактирования',
    'Email': 'Электронная почта',
    'Email options': 'Параметры электронной почты',
    'Enable': 'Активировать',
    'Enum': 'Перечисление',
    'Enum item': 'Элемент перечисления',
    'Enum items': 'Элементы перечислений',
    'Enumeration': 'Перечисление',
    'Enumeration source': 'Источник перечисления',
    'Enumerations': 'Перечисления',
    'Enums': 'Перечисления',
    'Error message': 'Сообщение об ошибке',
    'Escape': 'Экранировать',
    'Escape HTML data output': 'Экранировать вывод HTML данных',
    'Expanded group or active tab': 'Развернутая группа или активная вкладка',
    'Export': 'Экспортировать',
    'Export class': 'Экспортировать класс',
    'Export metadata': 'Экспортировать метаданные',
    'Export navigation section': 'Экспортировать секцию навигации',
    'Export section': 'Экспортировать секцию',
    'Export view': 'Экспортировать представление',
    'Expression': 'Выражение',
    'Expression options': 'Параметры выражения',
    'Expression or class configuration for calculating required value': 'Выражение или конфигурация класса для вычисления требуемого значения',
    'Extended hint': 'Расширенная подсказка',
    'Extensions': 'Расширения',

    'Featured classes for creating objects': 'Избранные классы для создания объектов',
    'File': 'Файл',
    'File options': 'Файловые параметры',
    'Filename attribute': 'Атрибут названия файла',
    'Filter': 'Фильтр',
    'Filter condition or class configuration for custom query related objects': 'Условие фильтрации или конфигурация класса для пользовательской выборки связанных объектов',
    'Filter condition to search for unique values.\nInput attribute name to create a filter by value of this attribute': 'Условие фильтра для поиска уникальных значений.\nВведите имя атрибута для создания фильтра по значению этого атрибута',
    'Filter selected files by type (e.g. image/jpeg)': 'Фильтровать выбираемые файлы по типу (например, image/jpeg)',
    'Final state': 'Конечное состояние',
    'Final states': 'Конечные состояния',
    'Finder': 'Искатель',
    'Finishing transitions': 'Заканчивающиеся переходы',
    'Flags': 'Флаги',
    'Float': 'Вещественный',
    'Forbidden view': 'Запрещенное представление',
    'Form values condition activating this enumeration': 'Условие значений формы, активирующее это перечисление',

    'Grouping': 'Группировка',
    'Group': 'Группа',
    'Groups': 'Группы',

    'Header': 'Заголовок',
    'Header template': 'Шаблон заголовка',
    'Hidden': 'Скрыто',
    'Hidden attribute view': 'Скрытое представление атрибута',
    'Hide attribute with empty value': 'Скрыть атрибут с пустым значением',
    'Hide empty': 'Скрыть пустой',
    'Hierarchy': 'Иерархия',
    'Hint': 'Подсказка',
    'Hint is displayed when hovering over an attribute label': 'Подсказка отображается при наведении курсора на ярлык атрибута',
    'History': 'История',

    'Identifier': 'Идентификатор',
    'Ignore case': 'Игнорировать регистр',
    'Ignore case when searching for matches': 'Игнорировать регистр при поиске совпадений',
    'Image only': 'Только изображения',
    'Import class': 'Импортировать класс',
    'Import metadata': 'Импортировать метаданные',
    'Import navigation section': 'Импортировать секцию навигации',
    'Import view': 'Импортировать представление',
    'In bytes': 'В байтах',
    'Index': 'Индекс',
    'Indexes': 'Индексы',
    'Indexing': 'Индексирование',
    'Inherit': 'Наследовать',
    'Inherited': 'Унаследованно',
    'Integer': 'Целое',
    'Integer only': 'Только целые',
    'Invalid class file': 'Неверный файл класса',
    'Invalid code name': 'Неверное кодовое имя',
    'Items': 'Элементы',
    'Intermediate link': 'Промежуточная связь',
    'Is not integer': 'Не является целым числом',
    'Is not sortable': 'Не является сортируемым',

    'JSON editor': 'Редактор JSON',

    'Keep history of attribute value changes': 'Сохранять историю изменений значения атрибута',
    'Key': 'Ключ',
    'Key attribute will be used for empty value': 'При пустом значении будет использован ключевой атрибут',

    'Length': 'Длина',
    'Limit the loading depth of nested related objects': 'Ограничение глубины загрузки вложенных связанных объектов',
    'Link attribute': 'Атрибут связи',
    'List limit': 'Предел списка',
    'List search': 'Поиск в списке',
    'List view': 'Представление списка',
    'Load related objects along with the main': 'Загружать связанные объекты вместе с основным',
    'Local date': 'Локальная дата',
    'Local date and time': 'Локальная дата и время',
    'Location': 'Местоположение',

    'Main': 'Главная',
    'Many related objects possible': 'Разрешить множество связанных объектов',
    'Maximum': 'Максимум',
    'Maximum files': 'Максимум файлов',
    'Maximum items': 'Максимум объектов',
    'Maximum length': 'Максимальная длина',
    'Maximum number of nested levels of related search filter objects': 'Максимальное количество вложенных уровней связанных объектов фильтра поиска',
    'Maximum objects': 'Максимум объектов',
    'Maximum size': 'Максимальный размер',
    'Maximum total size': 'Предел общего размера',
    'Maximum value': 'Максимальное значение',
    'Message': 'Сообщение',
    'Mediation to select related objects': 'Промежуточная связь для выбора связанных объектов',
    'Meta': 'Мета',
    'Metadata': 'Метаданные',
    'Metadata class': 'Класс метаданных',
    'Metadata deleted': 'Метаданные удалены',
    'Metadata directory relative to application root': 'Директория метаданных относительно корня приложения',
    'Metadata imported': 'Метаданные импортированы',
    'Metadata reloaded': 'Метаданные перезагружены',
    'MIME types': 'MIME типы',
    'Minimum': 'Минимум',
    'Minimum files': 'Минимум файлов',
    'Minimum length': 'Минимальная длина',
    'Minimum items': 'Минимум объектов',
    'Minimum objects': 'Минимум объектов',
    'Minimum size': 'Минимальный размер',
    'Minimum value': 'Минимальное значение',
    'Mismatch': 'Несовпадение',
    'Mismatch (valid if pattern does not match)': 'Несовпадение (валидно, если не соответствует шаблону)',
    'Model configuration': 'Конфигурация модели',
    'Multiple link': 'Множественная связь',

    'Navigation': 'Навигация',
    'Navigation node': 'Пункт навигации',
    'Navigation nodes': 'Пункты навигации',
    'Navigation section': 'Секция навигации',
    'Navigation section imported': 'Секция навигации импортирована',
    'Navigation sections': 'Секции навигации',
    'Nested groups': 'Вложенные группы',
    'New version': 'Новая версия',
    'New version replaces the current class when creating objects and uses shared storage': 'Новая версия заменяет текущий класс при создании объектов и использует общее хранилище',
    'Node': 'Пункт',
    'Nodes': 'Пункты',
    'None': 'Нет',
    'Null': 'Обнуление',
    'Null start state': 'Пустое начальное состояние',
    'Null state': 'Пустое состояние',
    'Number': 'Число',
    'Number options': 'Числовые параметры',

    'Object filter': 'Объектный фильтр',
    'Object in this view is read-only': 'Объект в этом представлении доступен только для чтения',
    'Object list grouping (e.g. {attrName: 1})': 'Группировка объектов в списке (например {attrName: 1})',
    'Object list order (e.g. {attrName: 1})': 'Порядок объектов в списке (например {attrName: 1})',
    'Object selection condition': 'Условие выборки объектов',
    'On create': 'При создании',
    'On delete': 'При удалении',
    'On update': 'При обновлении',
    'Options': 'Опции',
    'Orderable': 'Упорядочиваемый',    
    'Original': 'Оригинал',
    'Original class': 'Исходный класс',
    'Override': 'Переопределить',
    'Owner': 'Владелец',

    'Param': 'Параметр',
    'Params': 'Параметры',
    'Parent': 'Родитель',
    'Parent class attribute': 'Атрибут родительского класса',
    'Parent group': 'Родительская группа',
    'Parent node': 'Родительский пункт',
    'Pattern': 'Шаблон',
    'Predefined sets of named values': 'Предопределенные наборы именованных значений',
    'Primary key': 'Первичный ключ',

    'Query filter': 'Фильтр запроса',

    'Read-only': 'Только чтение',
    'Read-only mode': 'Режим только для чтения',
    'Reference': 'Ссылка',
    'Reference attribute': 'Ссылочный атирбут',
    'Reference class': 'Ссылочный класс',
    'Regular expression': 'Регулярное выражение',
    'Regular expression options': 'Параметры регулярного выражения',
    'Relation': 'Отношение',
    'Relation counter': 'Счетчик отношения',
    'Relation counter options': 'Параметры счетчика отношения',
    'Remove spaces from both ends of an attribute value': 'Удалить пустые символы с обоих концов значения атрибута',
    'Report': 'Отчет',
    'Report imported': 'Отчет импортирован',
    'Reports': 'Отчеты',
    'Require': 'Требовать',
    'Required': 'Обязательно',
    'Recursive': 'Рекурсивно',
    'Root folder of view templates (relative to the base location)': 'Корневая папка шаблонов представлений (относительно базового расположения)',
    'Rule': 'Правило',
    'Rules': 'Правила',

    'Save changes first': 'Сначала сохраните изменения',
    'Search': 'Поиск',
    'Search depth': 'Глубина поиска',
    'Search view': 'Представление поиска',
    'Searchable': 'Поисковый',
    'Section': 'Секция',
    'Select list view': 'Представление выбора',
    'Select searchable': 'Поисковый в списке выбора',
    'Separate with comma': 'Разделять запятой',
    'Setting': 'Настройка',
    'Show': 'Показать',
    'Sort': 'Сортировать',
    'Sort order': 'Порядок сортировки',
    'Sort order options': 'Параметры порядка сортировки',
    'Sortable': 'Сортируемо',
    'Sortable relation': 'Сортируемое отношение',
    'Sorting': 'Сортировка',
    'Sorting related objects within owner (non-indexable sorting)': 'Сортировка связанных объектов внутри владельца (не индексируемая выборка)',
    'Source': 'Источник',
    'Source class': 'Исходный класс',
    'Spawn configuration': 'Конфигурация создания',
    'Start': 'Начало',
    'Start state': 'Начальное состояние',
    'Start states': 'Начальные состояния',
    'Start value': 'Начальное значение',
    'Starting transitions': 'Начинающиеся переходы',
    'State': 'Состояние',
    'States': 'Состояния',
    'Step': 'Шаг',
    'Stored data type': 'Тип хранимых данных',
    'String': 'Строка',
    'String options': 'Строковые параметры',
    'String view template': 'Шаблон строкового представления',
    'String view template of object': 'Шаблон строкового представления объекта',
    'System attribute must be read only': 'Системный атрибут должен быть только для чтения',
    'System user': 'Системный пользователь',

    'Tab container': 'Контейнер вкладок',
    'Template root': 'Корень шаблонов',
    'Text': 'Текст',
    'The state will be automatically set for new objects': 'Состояние будет автоматически установлено для новых объектов',
    'Thumbnail': 'Миниатюра',
    'Time': 'Время',
    'Timestamp': 'Метка времени',
    'Timestamp options': 'Параметры метки времени',
    'Title': 'Заголовок',
    'Transit configuration': 'Конфигурация транзита',
    'Transit instantiation configuration': 'Конфигурация создания транзита',
    'Transition': 'Переход',
    'Transition is available if object condition is true': 'Переход доступен, если условие объекта истинно',
    'Transitions': 'Переходы',
    'Transitions ending in this state': 'Переходы, заканчивающиеся в этом состоянии',
    'Transitions starting from this state': 'Переходы, начинающиеся с этого состояния',
    'Tree level': 'Древовидный уровень',
    'Tree view': 'Древовид',
    'Tree view levels': 'Древовидные уровни',
    'Trim': 'Обрезать',

    'Unable to delete inherited attribute': 'Нельзя удалить унаследованный атрибут',
    'Unique': 'Уникально',
    'Unique key value': 'Уникальное значение ключа',
    'Uniqueness': 'Уникальность',
    'Uniqueness options': 'Параметры уникальности',
    'Update indexes': 'Обновить индексы',
    'Update timestamp': 'Метка обновления',
    'Used when class instance updating is forbidden by security': 'Используется, если изменение объекта класса запрещено безопасностью',
    'User': 'Пользователь',

    'Valid file extensions (e.g. png)': 'Допустимые расширения файлов (например png)',
    'Valid MIME types (e.g. image/png)': 'Допустимые MIME типы (например image/png)',
    'Validator': 'Валидатор',
    'Validator type': 'Тип валидатора',
    'Validators': 'Валидаторы',
    'Value': 'Значение',
    'Value attribute': 'Атрибут значения',
    'Valued': 'Имеющий значение',
    'Version': 'Версия',
    'View': 'Представление',
    'View attribute': 'Атрибут представления',
    'View attributes': 'Атрибуты представления',
    'View for eager loading of related objects': 'Представление для жадной загрзки связанных объектов',
    'View group': 'Группа представления',
    'View groups': 'Группы представления',
    'View imported': 'Представление импортировано',
    'View rule': 'Правило представления',
    'View to display related objects in a list': 'Представление для отображения связанных объектов в списке',
    'View to display objects in selection list': 'Представление для отображения объектов в списке выбора',
    'View type': 'Тип представления',
    'View used to create an object': 'Представление используемое для создания объекта',
    'View used to edit an object': 'Представление используемое для редакирования объекта',
    'Views': 'Представления',

    'When deleting an instance of a reference class:\nNull - empty linked attribute value\nCascade - delete relation owner instance': 'При удалении объекта ссылочного класса:\nОбнуление - очистить значение связи\nКаскадное действие - удалить объект владельца данного отношения',
    'When updating an instance of a reference class:\nNull - empty linked attribute value\nCascade - update linked attribute value': 'При обновлении объекта ссылочного класса:\nОбнуление - очистить значение связи\nКаскадное действие - обновить атрибут связи',
    'Workflow': 'Бизнес-процесс',
    'Workflow state': 'Состояние бизнес-процесса'
});