/**
 * @copyright Copyright (c) 2020 Maxim Khorin <maksimovichu@gmail.com>
 */
'use strict';

module.exports = {

    'component/Param': require('../component/param/Param'),
    'component/ParamContainer': require('../component/param/ParamContainer'),

    'export/ActionBinderExport': require('../component/export/ActionBinderExport'),
    'export/ClassAttrExport': require('../component/export/ClassAttrExport'),
    'export/ClassBehaviorExport': require('../component/export/ClassBehaviorExport'),
    'export/ClassBranchExport': require('../component/export/ClassBranchExport'),
    'export/ClassExport': require('../component/export/ClassExport'),
    'export/ClassGroupExport': require('../component/export/ClassGroupExport'),
    'export/ClassIndexExport': require('../component/export/ClassIndexExport'),
    'export/ClassRuleExport': require('../component/export/ClassRuleExport'),
    'export/EnumExport': require('../component/export/EnumExport'),
    'export/EnumItemExport': require('../component/export/EnumItemExport'),
    'export/Exporter': require('../component/export/Exporter'),
    'export/ExportModel': require('../component/export/ExportModel'),
    'export/FileBehaviorExport': require('../component/export/FileBehaviorExport'),
    'export/MetaExport': require('../component/export/MetaExport'),
    'export/NodeExport': require('../component/export/NodeExport'),
    'export/ReportAttrExport': require('../component/export/ReportAttrExport'),
    'export/ReportExport': require('../component/export/ReportExport'),
    'export/SectionExport': require('../component/export/SectionExport'),
    'export/StateExport': require('../component/export/StateExport'),
    'export/TimestampBehaviorExport': require('../component/export/TimestampBehaviorExport'),
    'export/TransitionExport': require('../component/export/TransitionExport'),
    'export/TreeViewExport': require('../component/export/TreeViewExport'),
    'export/ViaExport': require('../component/export/ViaExport'),
    'export/ViewAttrExport': require('../component/export/ViewAttrExport'),
    'export/ViewBehaviorExport': require('../component/export/ViewBehaviorExport'),
    'export/ViewExport': require('../component/export/ViewExport'),
    'export/ViewGroupExport': require('../component/export/ViewGroupExport'),
    'export/ViewRuleExport': require('../component/export/ViewRuleExport'),

    'import/ClassAttrImport': require('../component/import/ClassAttrImport'),
    'import/ClassGroupImport': require('../component/import/ClassGroupImport'),
    'import/ClassImport': require('../component/import/ClassImport'),
    'import/EnumImport': require('../component/import/EnumImport'),
    'import/ImportHelper': require('../component/import/ImportHelper'),
    'import/InheritedClassAttrImport': require('../component/import/InheritedClassAttrImport'),
    'import/InheritedClassGroupImport': require('../component/import/InheritedClassGroupImport'),
    'import/InheritedViaImport': require('../component/import/InheritedViaImport'),
    'import/MetaImport': require('../component/import/MetaImport'),
    'import/NodeImport': require('../component/import/NodeImport'),
    'import/ReportAttrImport': require('../component/import/ReportAttrImport'),
    'import/ReportImport': require('../component/import/ReportImport'),
    'import/SectionImport': require('../component/import/SectionImport'),
    'import/TreeViewImport': require('../component/import/TreeViewImport'),
    'import/ViaImport': require('../component/import/ViaImport'),
    'import/ViewAttrImport': require('../component/import/ViewAttrImport'),
    'import/ViewGroupImport': require('../component/import/ViewGroupImport'),
    'import/ViewImport': require('../component/import/ViewImport'),

    'other/HierarchySolver': require('evado/component/other/HierarchySolver'),

    'model/ActionBinder': require('../model/ActionBinder'),
    'model/AttrBehavior': require('../model/AttrBehavior'),
    'model/AttrRule': require('../model/AttrRule'),    
    'model/Class': require('../model/Class'),
    'model/ClassAttr': require('../model/ClassAttr'),
    'model/ClassBehavior': require('../model/ClassBehavior'),
    'model/ClassGroup': require('../model/ClassGroup'),
    'model/ClassIndex': require('../model/ClassIndex'),
    'model/ClassIndexAttr': require('../model/ClassIndexAttr'),
    'model/ClassRule': require('../model/ClassRule'),    
    'model/Enum': require('../model/Enum'),
    'model/EnumItem': require('../model/EnumItem'),
    'model/Node': require('../model/Node'),
    'model/Report': require('../model/Report'),
    'model/ReportAttr': require('../model/ReportAttr'),
    'model/ReportGroup': require('../model/ReportGroup'),
    'model/Section': require('../model/Section'),
    'model/State': require('../model/State'),
    'model/Transition': require('../model/Transition'),
    'model/TreeViewLevel': require('../model/TreeViewLevel'),
    'model/Via': require('../model/Via'),
    'model/View': require('../model/View'),
    'model/ViewAttr': require('../model/ViewAttr'),
    'model/ViewAttrBehavior': require('../model/ViewAttrBehavior'),
    'model/ViewAttrRule': require('../model/ViewAttrRule'),
    'model/ViewBehavior': require('../model/ViewBehavior'),
    'model/ViewGroup': require('../model/ViewGroup'),
    'model/ViewRule': require('../model/ViewRule'),
    'model/Workflow': require('../model/Workflow')
};